 const eng={
    appname:"PakLoaders",
    getLuggage:"Get your luggage insured",
    luggageInsurance:"Luggage insurance is provided in case of loss or any damage of luggage",
    safe:"Safe and fast service",
    safty:"On time trip service is being provided with complete safety of luggage.",
    easyBook:"Easy to book a trip anytime all over Pakistan",
    language :"Language ",
    selectLanguage:"Please select a language",
    english:"English",
    urdu:"Urdu",
    // Login screen
    // loginin: "Login In",
    loginowner:"Login as Owner",
    logindriver:"Login as Driver",
    //Sign in
    signin: "Sign In",
    doNotHaveAnAccount: "do not have an account?",
    // Signup screen
    mobileNum:"Mobile Number",
    password:"Password",
    signUp:"Sign Up",
    fullName:"Full name",
    confirmPass:"Confirm Password",
    // verification
    accountVerification: "Account Verification",
    veriCode:"Haven't received a code?",
    sendAgain: "Send Again",
    verify:"Verify",
    // verified screen
    verified: "verified!!",
    veriSuccess:"You have successfully verified the account. ",
    ok:"Ok",
   //  Basic Screen info
   Welcome:"Welcome John Smith",
   completProfile:"Please complete your profile to proceed",
   fname:"First name ",
   lname:"Last name",
   dob:"Date of birth",
   SmNum:"Secondary mobile number",
   next:"Next ",
   cancel:"Cancel ",
   // Cnic details screen
   fimage:"front image of CNIC",
   bimg:"back image of cnic",
   cnic:"Cnic number",
   issueDate:"Issue date",
   expiryDate:"Expiry date",
   // Id confirmation
   vehicleInfo:"Vehicle Info",
   vehicleImg:"Add Vehicle image",
   vehicleReg:"Vehicle registration number",
   inssurnaceNum:"Insurance number",
   modelNum:"Model number",
   save:"Save",
   drivingLicence:"Driver License",
   licenceImg:"Front image of license",
   bLicenceImg:"Back image of license",
   licenceNum:"License number",
   // Ownership verification
   ownership:"Ownership verification",
   owner:"I am the owner of the vehicle",
   other:"Other",
   ownerVeriCode:"We will send you a verification code to the owner of the vehicle",
   fullName:"Full name",
   close:"Close",
   submit:"Submit",
   fpassword:"Forgot password",
   conf:"Confirm",
   resetPass:"Reset Password",
   newPass:"New Password",
   search:"Search",
   newBids:"New bids",
   pickUp:"pick up",
   dropOff:"drop off",
   dateOfPickup:"date of pick up",
  //  viewDetail:"(View details) in bids home screen ",
   viewDetails: "View details",
   bidsReq:"Bids Requests",
   sendBidRequest: "Send Bid Request",

   myEarning:"My Earnings",
   rating:"Rating",
   priceRange:"Price range ",
   distance:"Distance",
   apply:"Apply",
   close:"Close ",
   viewDetailScreen:"View Details Screen",
   bidDetails:"Bid Details",
   timing:"Timing",
   charges:"Charges",
   weight:"Weight",
   ignore:"Ignore",
   bid:"Bid",
   amountmention:"Ammount Mentioned",
   bidOnRequestedCharges:"Bid on requested charges",
   bidOnCustomCharges:"Bid on custom charges",
   bidAmount:"Your bid ammount",
   close:"Close",
   bidPlace:"Place bid",
   chats:"Chats",
   ongoing:"Ongoing",
   upcoming:"Upcoming",
   complete:"Completed",
   canceled:"Canceled",
   arrivalTime:"Arrival time",
   vehicleNum:"Vehicle No.",
   pickUpDate:"Pick up date",
   payment:"Payment",
   tripComplete:"Trip completed",
   endRide:"End ride",
   rideDetail:"Ride Detail",
   reciverNum:"Receiver name",

   amountPayed:"Amount payed",
   experience:"Please share your experience with us",
   feedback:"Wrie your feedback",
   essentialFeatures:"Essential 4Features",
   unlimitedLoad:"Unlimited load views",
   annualPlan:"Annual plan",
   creditCard:"Credit / Debit Card",
   easypaisa:"Easypaisa",
   jazzcash:"Jazzcash",
   bankAccount:"Bank Account",
   payNow:"Pay Now",
   cardHolder:"Card holder name",
   cardNumber:"Card number ",
   monthYearCv:"Month, year, cvv",
   jazzcashNumber:"Pay with your jazzcash account. Enter the jazzcash registered mobile number",
    jazzcshMobileNumber:"Jazzcash mobile number",
    Mpin:"Mpin",
    tripsCompleted:"Trips completed",
    tripsInprogress:"Trips inprogress ",
    tripCanceled:"Trips canceled",
    subscriptionDtail:"Trips canceled",
    dateOfSub:"Date of subscription",
    annualSub:"Your subscription for prefered annual plan has expired. Please resubscribed to get access.",
    vehicleAdd:"Vehicle added",
    changePass:"Change Password",
    customerReview:"Customer reviews",
    secondMobNo:"Secondary Mobile no",
    oldPass:"Old Password",
    bankAccountDetail:"Pay with your Bank account. Enter the Account details",
    easypaisaDetail:"Pay with your Easypaisa Direct account. Enter the Easypaisa registered mobile number",
    
   //  Custom Drawer
   home:"Home",
    editPost:"Edit Post",
    newPost: "New Post",
    packages:"Packages",
    insuredLuggage:"Insured Luggage",
    myRides:"My Rides",
    myPost:"My Post",
    chat:"Chat",
    payment:"Payment",
    share:"Share",
    contactUs:"Contact Us",
    rate:"Rate",
    logOut:"Log Out",
    myBids: "My Bids",
    MyProfile: "My Profile",
    rides: "Rides",
    rateUs: "Rate us",

   //  Custom Drawer
    addPost:"Add Post",
    createPost:"Create Post",
   //  Custom Drawer
   vehicleDetail:"Vehicle Details",
   vehicleModel:"vehicle model",
   // Earning Screen
   tripId:"Trip Id",
   troubleContact:"having trouble contact us",
   email:"Email",
   description:"Description",
   customers:"Customers",
   bidTime:"Bid Time",
   bidRank:"Bid Rank",
   pickupLocation:"pickup location",
   insurnacePack:"Luggage insurance package",
   purchasePlan:"Please purchase any plan to get your luggage insured",
   unlockFeature:"Unlock 4 Powerful Features",
   fourFeacture:"4 Features",
   thirteenFeacture: "13 Features",
   essential:"Essential",
   bankNote:"Note: Ensure your Bank account is active and has sufficient balance.",
   postDetail:"Post Detail",
   accept:"Accept",
   profileProcess:"Please complete your profile to proceed",
   Prefrered:"Prefrered",
   sevenFeatures:"7 Features",
   ultimate:"Ultimate",
   feature:"Feature",
   daystoPay:"Days to Pay & Credit Score",
   easypaisaNote:"Note: Ensure your Easypaisa Direct account is active and has sufficient balance.",
 }
   
const Urdu={
  easypaisaNote:"نوٹ: یقینی بنائیں کہ آپ کا Easypaisa ڈائریکٹ اکاؤنٹ ہے۔ فعال اور کافی توازن ہے.",

  easypaisaDetail:"اپنے Easypaisa ڈائریکٹ اکاؤنٹ سے ادائیگی کریں۔ ایزی پیسہ رجسٹرڈ موبائل نمبر درج کریں۔",

  daystoPay:"ادائیگی اور کریڈٹ سکور کے دن",

  feature:"خصوصیت",

  ultimate:"حتمی",

  sevenFeatures: " 7 " + "خصوصیات",

  Prefrered:"ترجیحی",
  profileProcess:"آگے بڑھنے کے لیے براہ کرم اپنا پروفائل مکمل کریں۔",

  accept:"قبول کریں",

  postDetail:"پوسٹ تفصیل",

  bankNote:"نوٹ: یقینی بنائیں کہ آپ کا بینک اکاؤنٹ فعال ہے اور کافی بیلنس ہے۔",
  bankAccountDetail:"اپنے بینک اکاؤنٹ سے ادائیگی کریں۔ اکاؤنٹ کی تفصیلات درج کریں۔",
  essential:"ضروری",
  fourFeacture: " 4 " + "خصوصیات",
  thirteenFeacture: " 13 " + "خصوصیات",
  unlockFeature:"4 طاقتور خصوصیات کو غیر مقفل کریں",
   purchasePlan:"براہ کرم اپنے سامان کی بیمہ کروانے کے لیے کوئی بھی منصوبہ خریدیں۔",
   insurnacePack:"سامان کا انشورنس پیکج",
    appname:"پاک لوڈرز",
    getLuggage:"اپنے سامان کی بیمہ کروائیں۔",
    luggageInsurance:"سامان کے نقصان یا کسی نقصان کی صورت میں سامان کی انشورنس فراہم کی جاتی ہے",
    safe:"محفوظ اور تیز سروس",
    safty:"سامان کی مکمل حفاظت کے ساتھ آن ٹائم ٹرپ سروس فراہم کی جا رہی ہے",
    easyBook:"پورے پاکستان میں کسی بھی وقت ٹرپ بک کرنا آسان ہے",
    language :"زبان",
    selectLanguage:"براہ کرم ایک زبان منتخب کریں",
    english:"انگریزی",
    urdu:"اردو",
    // Login screen
    loginowner:"مالک کے طور پر لاگ ان کریں",
    logindriver:"ڈرائیور کے طور پر لاگ ان کریں",
    // Sign In 
    signin: "سائن ان",
    doNotHaveAnAccount: "کھاتہ نہیں ہے کیا؟",
    // Signup screen
    mobileNum:"موبائل نمبر",
    password:"پاس ورڈ",
    signUp:"سائن اپ",
    fullName:"پورا نام",
    confirmPass:"پاس ورڈ کی تصدیق کریں",
    // verification
    accountVerification: "اکاؤنٹ کی تصدیق",
    sendAgain: "دوبارہ بھیجو",
    veriCode:"کوڈ موصول نہیں ہوا؟",
    verify:"تصدیق کریں",
    // verified screen
    verified: "تصدیق شدہ!!",
    veriSuccess:"آپ نے کامیابی سے اکاؤنٹ کی تصدیق کر لی ہے ",
    ok:"ٹھیک ہے",
   //  Basic Screen info
   Welcome:"خوش آمدید جان سمتھ",
   completProfile:"براہ کرم آگے بڑھنے کے لیے اپناپروفائل مکمل کریں",
   fname:"پہلا نام ",
   lname:"آخری نام",
   dob:"پیدائش کی تاریخ",
   SmNum:"ثانوی موبائل نمبر",
   next:"اگلے",
   cancel:"منسوخ ",
   // Cnic details screen
   fimage:"کی سامنے کی تصویر CNIC",
   bimg:"کی پچھلی تصویر CNIC",
   cnic:"نمبر Cnic",
   issueDate:"تاریخ اجراء",
   expiryDate:"خاتمے کی تاریخ",
   // Id confirmation
   vehicleInfo:"گاڑی کی معلومات",
   vehicleImg:"گاڑی کی تصویر شامل کریں",
   vehicleReg:"گاڑی کا رجسٹریشن نمبر",
   inssurnaceNum:"انشورنس نمبر",
   modelNum:"ماڈل نمبر",
   save:"محفوظ کریں",
   drivingLicence:"ڈرائیور لائسنس",
   licenceImg:"لائسنس کی سامنے کی تصویر",
   bLicenceImg:"لائسنس کی پچھلی تصویر",
   licenceNum:"لائسنس نمبر",
   // Ownership verification
   ownership:"ملکیت کی تصدیق",
   owner:"میں گاڑی کا مالک ہوں",
   other:"دوسرے",
   ownerVeriCode:"ہم آپ کو گاڑی کے مالک کو ایک تصدیقی کوڈ بھیجیں گے",
   fullName:"پورا نام",
   close:"بند کریں",
   submit:"جمع کرائیں",
   fpassword:"پاسورڈ بھول گے",
   conf:"تصدیق کریں",
   resetPass:"پاس ورڈ ری سیٹ",
   newPass:"نیا پاس ورڈ",
   search:"تلاش کریں",
   newBids:"نئی بولیاں",
   pickUp:"اٹھاؤ",
   dropOff:"چھوڑ",
   dateOfPickup:"لینے کی تاریخ",
   viewDetail:"تفصیل دیکھیں",
   bidsReq:"بولی کی تفصیلات",
   sendBidRequest: "بولی کی درخواست بھیجیں",
   myEarning:"میری کمائی",
   rating:"درجہ بندی",
   priceRange:"قیمت کی حد",
   distance:"فاصلہ",
   apply:"درخواست دیں",
   close:"بند کریں",
   viewDetailScreen:"تفصیل دیکھیں",
   viewDetails: "تفصیلات دیکھیں",
   bidDetails:"بولی کی تفصیلات",
   timing:"ٹائمنگ",
   charges:"چارجز",
   weight:"وزن",
   ignore:"نظر انداز",
   bid:"بول",
   amountmention:"ذکر شدہ رقم",
   bidOnRequestedCharges: "درخواست کردہ چارجز پر بولی لگائیں",
   bidOnCustomCharges:"اپنی مرضی کے چارجز پر بولیاں",
   bidAmount:"]آپ کی بولی کی رقم",
   close:"بند کریں",
   bidPlace:"جگہ کی بولی",
   chats:"چیٹس",
   ongoing:"جاری ہے",
   upcoming:"آنے والا",
   complete:"مکمل",
   canceled:"منسوخ",
   arrivalTime:"آمد کے وقت",
   vehicleNum:"گاڑی نمبر",
   pickUpDate:"تاریخ اٹھاو",
   payment:"ادائیگی",
   tripComplete:"سفر مکمل",
   endRide:"سواری ختم",
   rideDetail:"سواری کی تفصیلات",
   reciverNum:"وصول کنندہ کا نام",
   amountPayed:"رقم ادا کر دی",
   experience:"براہ کرم اپنا تجربہ ہمارے ساتھ شیئر کریں",
   feedback:"پنی رائے لکھیں",
   essentialFeatures:"ضروری 4 خصوصیات ",
   unlimitedLoad:"لامحدود لوڈ ویوز",
   annualPlan:"سالانہ منصوبہ",
   creditCard:"]کریڈٹ/ڈیبٹ کارڈ",
   easypaisa:"Easypaisa",
   jazzcash:"Jazzcash",
   bankAccount:"بینک اکاؤنٹ",
   payNow:"ادائیگی",
   cardHolder:"کارڈ ہولڈر کا نام",
   cardNumber:"کارڈ نمبر ",
   monthYearCv:"مہینہ، سال، سی وی وی",
   jazzcashNumber:"رجسٹرڈ موبائل نمبر درج کریں۔  Jazzcashاکاؤنٹ سے ادائیگی کریں۔  jazzcashاپنے",
    jazzcshMobileNumber:"موبائل نمبر Jazzcash",
    Mpin:"Mpin",
    tripsCompleted:"سفر مکمل",
    tripsInprogress:"سفر جاری ہے",
    tripCanceled:"سفر منسوخ",
    subscriptionDtail:"سبسکرپشن کی تفصیلات",
    dateOfSub:"سبسکرپشن کی تاریخ",
    annualSub:"دوبارہ سبسکرائب کریںn ترجیحی سالانہ پلان کے لیے آپ کی رکنیت ختم ہو گئی ہے۔ رسائی حاصل کرنے کے لیے براہ کرم",
    vehicleAdd:"گاڑی شامل کی گئی",
    changePass:"پاس ورڈ تبدیل کریں",
    customerReview:"کسٹمر کے جائزے",
    secondMobNo:"سیکنڈری موبائل نمبر",
    oldPass:"پرانا پاسورڈ",
    //  Custom Drawer
    home:"ہوم",
    editPost:"پوسٹ میں ترمیم کریں",
    newPost: "نئی پوسٹ",
    packages:"پیکجز",
    myBids: "میری بولیاں",
    MyProfile: "میرا پروفائل",
    rateUs: "ہمیں درجہ دیں",
    rides: "سواریاں",
    insuredLuggage:"بیمہ شدہ سامان",
    myRides:"میری سواریاں",
    myPost:"میری پوسٹ",
    chat:"گپ شپ",
    payment:"ادائیگی",
    share:"بانٹیں",
    contactUs:"ہم سے رابطہ کریں",
    rate:"شرح",
    logOut:"لاگ آوٹ",
   //  Custom Drawer
    addPost:"پوسٹ شامل کریں",
    createPost:"پوسٹ بنائیں",

   //  Custom Drawer
   vehicleDetail:"گاڑی کی تفصیلات",
   vehicleModel:"گاڑی کا رجسٹریشن نمبر",
   // Earning Screen
   tripId:"ٹرپ آئی ڈی",
   troubleContact:"پریشانی ہو ہم سے رابطہ کریں",
   email:"ای میل",
   description:"تفصیل",
   customers:"گاہکوں",
   bidTime:"بولی کا وقت",
   bidRank:"بولی کا درجہ",
   pickupLocation:"اٹھانے کا مقام",
   

 }

export {eng,Urdu};